export const data = {
    headphones: [
        {
            id: 1,
            img: "assets/Image.png",
            webp: "assets/Image.webp",
            title: "Apple BYZ S852I",
            price: 2927,
            previousPrice: 3527,
            rate: 4.7,
            wireless: false,
        },
        {
            id: 2,
            img: "assets/image-1.png",
            webp: "assets/image-1.webp",
            title: "Apple EarPods",
            price: 2327,
            rate: 4.5,
            wireless: false,
        },
        {
            id: 3,
            img: "assets/image-2.png",
            webp: "assets/image-2.webp",
            title: "Apple EarPods",
            price: 2327,
            rate: 4.5,
            wireless: false,
        },
        {
            id: 4,
            img: "assets/image.png",
            webp: "assets/image.webp",
            title: "Apple BYZ S852I",
            price: 2927,
            rate: 4.7,
            discount: "-20%",
            wireless: false,
        },
        {
            id: 5,
            img: "assets/image-1.png",
            webp: "assets/image-1.webp",
            title: "Apple EarPods",
            price: 2327,
            rate: 4.5,
            wireless: false,
        },
        {
            id: 6,
            img: "assets/image-2.png",
            webp: "assets/image-2.webp",
            title: "Apple EarPods",
            price: 2327,
            rate: 4.5,
            wireless: false,
        },
        {
            id: 7,
            img: "assets/image-5.png",
            webp: "assets/image-5.webp",
            title: "Apple AirPods",
            price: 9527,
            rate: 4.7,
            wireless: true,
        },
        {
            id: 8,
            img: "assets/image-3.png",
            webp: "assets/image-3.webp",
            title: "GERLAX GH-04",
            price: 6527,
            rate: 4.7,
            wireless: true,
        },
        {
            id: 9,
            img: "assets/image-4.png",
            webp: "assets/image-4.webp",
            title: "BOROFONE BO4",
            price: 7527,
            rate: 4.7,
            wireless: true,
        },
    ],
};
